### ISSUE TITLE
[QUESTION] Add message

### ISSUE THREAD

**Issue by oleteacher** [sujeetkrsingh/simple-jquery-countdown#1]
This is the simplest countdown plugin ever seen. Very easy to use and light weight, thank you for sharing!

Is there a way to create a custom message when counter reaches 0?

Be nice to have a simple message shown when countdown finished.

Cheers!

**Comment by sujeetkrsingh** [comment]
Hi Susan,
I am glad you like my plugin.
You can easily achieve your goal with a little modification in the plugin source code.
Open plugin file `countdown.js` which is inside js directory and replace the code at line number 14:

**`this.hide();`**

With this one:

**`this.html("This is the message after clock reaches 0");`**

**Comment by oleteacher** [comment]
Perfect, thank you @sujeetkrsingh 

I had it about right with my experiment, just one little error:)

Thank you again.
